### ISSUE TITLE
Remove Unnecessary Buttons

### ISSUE THREAD

**Issue by iharsh234** [iharsh234/WebApp#10]
![issue](https://user-images.githubusercontent.com/12688534/31314694-b416f5c6-ac24-11e7-86a7-10a26763e79e.JPG)

Highlighted in Image, Just remove them.

**Comment by bikrambhattacharya** [comment]
@iharsh234  I will take up this one

**Comment by duwalanise** [comment]
@bikrambhattacharya @iharsh234  i am so sorry i have created PR but forgot to inform you.

**Comment by iharsh234** [comment]
Closing this. Thanks All :1st_place_medal:
